Repository AY2122S1-TIC4001-F18-2/tp, pull requests merged in 2021-10, with the labels that each got.

#34 Enable Assertion Config
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/duke/UI.java
Labels: type.task

#41 v1.0 - JUnit&Logging
  src/main/java/seedu/duke/Duke.java
  src/test/java/seedu/duke/ParserTest.java
Labels: type.task

#65 Timing
  src/main/java/seedu/duke/ExpenseList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/AddExpenseCommand.java
  src/main/java/seedu/duke/command/AddIncomeCommand.java
  src/main/java/seedu/duke/expense/Expense.java
  src/test/java/seedu/duke/ExpenseListTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
Labels: type.epic

#92 Delete command test
  log/DeleteLogFile.log
  log/ExpensesTrackerLogFile.log
  log/ExpensesTrackerLogFile.log.lck
  log/ListLogFile.log
  log/ListLogFile.log.2
  log/ListLogFile.log.3
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
Labels: enhancement, type.task

#89 Add Expense Command Test
  log/DeleteLogFile.log
  log/ExpensesTrackerLogFile.log
  log/ExpensesTrackerLogFile.log.lck
  log/ListLogFile.log
  log/ListLogFile.log.2
  log/ListLogFile.log.3
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
Labels: enhancement, type.task

#93 Summary and Delete Command update
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Execution.java
  src/main/java/seedu/duke/InputErrorException.java
  src/main/java/seedu/duke/ItemList.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/UI.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/SummaryCommand.java
  src/main/java/seedu/duke/item/Expense.java
  src/main/java/seedu/duke/item/Income.java
  src/main/java/seedu/duke/item/Item.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
Labels: bug, type.story, type.task, priority.High
